name: Release

on:
  push:
    tags:
      - '*'

env:
  NUGET_API_TOKEN: ${{ SECRETS.NUGET_API_TOKEN }}

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET 3.1.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5.0.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Check .NET info
      run: dotnet --info

    - name: Install dependencies
      run: nuget restore

    - name: Build solution
      run: dotnet build -c Release --no-restore

    - name: Test solution
      run: dotnet test -c Release --no-build --no-restore --verbosity normal

    - name: Pack package
      run: dotnet pack -c Release -o packages --no-build;

    - name: Push nuget package
      run: dotnet nuget push .\packages\*.nupkg -s nuget.org -k $env:NUGET_API_TOKEN --skip-duplicate
